# Generated by Django 3.2.16 on 2024-06-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='', max_length=20, verbose_name='주문 번호'),
            preserve_default=False,
        ),
    ]
