# Generated by Django 3.2.16 on 2024-06-17 15:04

import cheonbaeksa.apps.orders.models.index
import cheonbaeksa.bases.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='삭제 여부')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.IntegerField(verbose_name='유저 ID')),
                ('product_id', models.IntegerField(verbose_name='상품 ID')),
                ('coupon_id', models.IntegerField(blank=True, null=True, verbose_name='쿠폰 ID')),
                ('number', models.CharField(default=cheonbaeksa.apps.orders.models.index.generate_unique_number, max_length=20, unique=True, verbose_name='주문 번호')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 가격')),
                ('status', model_utils.fields.StatusField(choices=[('PENDING', '진행'), ('APPROVED', '승인'), ('REFUSED', '거절')], default=None, max_length=100, no_check_for_status=True, null=True, verbose_name='상태')),
                ('pending_at', model_utils.fields.MonitorField(default=None, monitor='status', null=True, verbose_name='진행 시간', when={'PENDING'})),
                ('approved_at', model_utils.fields.MonitorField(default=None, monitor='status', null=True, verbose_name='승인 시간', when={'APPROVED'})),
                ('refused_at', model_utils.fields.MonitorField(default=None, monitor='status', null=True, verbose_name='거절 시간', when={'REFUSED'})),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created'],
            },
            bases=(cheonbaeksa.bases.models.UpdateMixin, models.Model),
        ),
    ]
