# Generated by Django 3.2.16 on 2024-06-17 12:34

import cheonbaeksa.apps.coupons.models.index
import cheonbaeksa.bases.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='삭제 여부')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.IntegerField(verbose_name='쿠폰을 발급한 유저 ID')),
                ('coupon_group_id', models.IntegerField(blank=True, null=True, verbose_name='쿠폰 그룹 ID')),
                ('code', models.CharField(default=cheonbaeksa.apps.coupons.models.index.generate_unique_code, max_length=12, unique=True, verbose_name='코드')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='할인 금액')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='할인 비율')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('expired', models.DateTimeField(verbose_name='만료 시간')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
                'ordering': ['-created'],
            },
            bases=(cheonbaeksa.bases.models.UpdateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CouponGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='삭제 여부')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='쿠폰 그룹을 생성한 유저의 ID')),
                ('title', models.CharField(max_length=100, verbose_name='타이틀')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='할인 금액')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='할인 비율')),
                ('valid_days', models.IntegerField(verbose_name='유효 기간 (일)')),
            ],
            options={
                'verbose_name': '쿠폰 그룹',
                'verbose_name_plural': '쿠폰 그룹',
                'ordering': ['-created'],
            },
            bases=(cheonbaeksa.bases.models.UpdateMixin, models.Model),
        ),
    ]
