# Generated by Django 3.2.16 on 2024-06-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_insert_default_product_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='상품을 생성한 유저의 ID'),
        ),
    ]
