# Generated by Django 3.2.16 on 2024-06-26 13:34

import cheonbaeksa.bases.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='삭제 여부')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_email', models.EmailField(max_length=254, verbose_name='보낸 사람 이메일')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='받는 사람 이메일')),
                ('title', models.CharField(max_length=100, verbose_name='타이틀')),
                ('content', models.TextField(verbose_name='본문')),
                ('purpose', models.CharField(choices=[('SIGNUP', '회원가입'), ('PASSWORD_RESET', '비밀번호 변경'), ('PASSWORD_RECOVERY', '비밀번호 찾기'), ('PAYMENT_COMPLETED', '결제 완료')], max_length=20, verbose_name='이메일 전송 목적')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='상태')),
            ],
            options={
                'verbose_name': '이메일 전송',
                'verbose_name_plural': '이메일 전송',
                'ordering': ['-created'],
            },
            bases=(cheonbaeksa.bases.models.UpdateMixin, models.Model),
        ),
    ]
