# Generated by Django 3.2.16 on 2024-06-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0002_alter_emailsend_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsend',
            old_name='sender_email',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='emailsend',
            old_name='recipient_email',
            new_name='to_email',
        ),
    ]
