# Generated by Django 3.2.16 on 2024-06-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='담당 어드바이저 ID'),
        ),
    ]
