# Generated by Django 3.2.16 on 2024-06-10 17:27

import cheonbaeksa.apps.verifications.models.email
import cheonbaeksa.bases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='삭제 여부')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('code', models.CharField(default=cheonbaeksa.apps.verifications.models.email.create_code, max_length=6, verbose_name='6자리 인증 코드')),
                ('purpose', models.CharField(choices=[('SIGNUP', '회원가입'), ('PASSWORD_RESET', '비밀번호 변경'), ('PASSWORD_RECOVERY', '비밀번호 찾기')], max_length=20, verbose_name='이메일 전송 목적')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 완료 여부')),
                ('expired', models.DateTimeField(verbose_name='만료 시간')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
                'ordering': ['-created'],
            },
            bases=(cheonbaeksa.bases.models.UpdateMixin, models.Model),
        ),
    ]
