# Generated by Django 3.2.16 on 2024-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP', '회원가입'), ('PASSWORD_RESET', '비밀번호 변경'), ('PASSWORD_RECOVERY', '비밀번호 찾기'), ('PAYMENT_COMPLETED', '결제 완료')], max_length=20, verbose_name='이메일 전송 목적'),
        ),
    ]
