# Generated by Django 3.2.16 on 2024-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0002_alter_emailverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP', '회원가입'), ('PASSWORD_RESET', '비밀번호 변경'), ('PASSWORD_RECOVERY', '비밀번호 찾기'), ('PAYMENT_COMPLETE', '결제 완료')], max_length=20, verbose_name='이메일 전송 목적'),
        ),
    ]
